name = "The-InBetween"
author = "Conquerix"
version = "v0.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caffafe4dc1aab48c5c911d77ccac727ab361d6baaf0fc96892b6e97bedd0975"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
